import argparse
import os
import re
import ast
import io
import json
import pandas as pd
import numpy as np
import plotly.express as px

def parse_tuning_logs(log_dir: str) -> pd.DataFrame:
    """
    Parses full CV results from log files generated by train.py.

    Args:
        log_dir: The directory containing the tuning log files.

    Returns:
        A DataFrame with columns ['params', 'mean_test_score', 'std_test_score'].
    """
    if not os.path.exists(log_dir):
        raise FileNotFoundError(f"Log directory does not exist: {log_dir}")

    if not os.path.isdir(log_dir):
        raise ValueError(f"Path is not a directory: {log_dir}")

    all_results = []
    log_files = [f for f in os.listdir(log_dir) if f.endswith('.log')]
    if not log_files:
        raise FileNotFoundError(f"No .log files found in directory: {log_dir}")

    print(f"Found {len(log_files)} log files to parse.")

    for filename in log_files:
        filepath = os.path.join(log_dir, filename)
        with open(filepath, 'r') as f:
            content = f.read()

            # Find the block of text between text markers
            try:
                start_marker = "--- START CV RESULTS ---"
                end_marker = "--- END CV RESULTS ---"
                start_index = content.find(start_marker)
                end_index = content.find(end_marker)

                if start_index == -1 or end_index == -1:
                    print(f"Warning: Could not find CV results block in {filename}. Skipping.")
                    continue

                # Extract the CSV-formatted string
                csv_content = content[start_index + len(start_marker) : end_index].strip()

                # Use pandas to read the string directly as if it were a file using the `io.StringIO` wrapper
                run_df = pd.read_csv(io.StringIO(csv_content))
                all_results.append(run_df)

            except Exception as e:
                print(f"Error parsing {filename}: {e}")

    if not all_results:
        raise ValueError("Failed to parse any valid CV results from log files. Run find_best_hyperparams.sbatch with train.py first")

    return pd.concat(all_results, ignore_index=True)


def analyse_and_select_params(df: pd.DataFrame, alpha: float) -> (dict, pd.DataFrame):
    """
    Analyses aggregated results and selects the best hyperparameter set.
    """
    # ast.literal_eval is a safe way to convert string representations of dicts
    # This is where we need the sanitised np.floats otherwise it breaks
    df['params_dict'] = df['params'].apply(ast.literal_eval)
    # Convert dict to a frozenset of items to make it hashable for grouping
    df['params_group'] = df['params_dict'].apply(lambda d: frozenset(d.items()))

    grouped = df.groupby('params_group')

    # Calculate aggregate statistics for each unique parameter set
    summary_list = []
    for name, group in grouped:
        summary_list.append({
            'params': dict(name), # Convert frozenset back to dict
            'mean_pr_auc': group['mean_test_score'].mean(),
            'std_pr_auc': group['mean_test_score'].std(),
            'num_folds_tested': len(group)
        })

    summary = pd.DataFrame(summary_list)
    summary['std_pr_auc'] = summary['std_pr_auc'].fillna(0)

    # Calculate the utility score and sort
    summary['utility_score'] = summary['mean_pr_auc'] - (alpha * summary['std_pr_auc'])
    summary = summary.sort_values('utility_score', ascending=False).reset_index(drop=True)

    best_params_dict = summary.loc[0, 'params']

    return best_params_dict, summary

def plot_pareto_front(df: pd.DataFrame, output_path: str):
    """
    Generates an interactive plot of the performance vs. stability trade-off.
    """
    print("Generating interactive Pareto plot...")
    
    fig = px.scatter(
        df,
        x='mean_pr_auc',
        y='std_pr_auc',
        color='utility_score',
        hover_data=['params', 'num_folds_tested'],
        labels={
            'mean_pr_auc': 'Mean PR-AUC (Performance)',
            'std_pr_auc': 'Std Dev of PR-AUC (Instability)',
            'utility_score': 'Utility Score'
        },
        title='Hyperparameter Performance vs. Stability'
    )

    fig.update_layout(
        xaxis_title='Mean Performance (Higher is Better)',
        yaxis_title='Instability (Lower is Better)',
    )
    
    fig.write_html(output_path)
    print(f"Saved interactive plot to {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Automatically select the best hyperparameters from cross-validation tuning logs.")
    parser.add_argument("--log-dir", type=str, default="tuning_logs", help="Directory containing the tuning run log files.")
    parser.add_argument("--alpha", type=float, default=1.0, help="Risk-aversion parameter. Higher values prioritise stability over raw performance.")
    parser.add_argument("--plot-path", type=str, default="final_results/hyperparameter_tradeoff.html", help="Path to save the interactive plot.")
    args = parser.parse_args()

    # --- Run Analysis ---
    raw_results_df = parse_tuning_logs(args.log_dir)
    best_params, summary_df = analyse_and_select_params(raw_results_df, args.alpha)

    print("\n--- Hyperparameter Analysis Summary ---")
    print("Top 5 parameter sets based on utility score:")
    print(summary_df.head(5))

    print("\n--- AUTOMATICALLY SELECTED BEST HYPERPARAMETERS ---")
    print("This set offers the best balance of performance and stability.")
    print(f"JSON object to copy: {json.dumps(best_params)}")
    
    if args.plot_path:
        os.makedirs(os.path.dirname(args.plot_path), exist_ok=True)
        plot_pareto_front(summary_df, args.plot_path)

if __name__ == "__main__":
    main()
